default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: usvers

test:
  <<: *default
  database: usvers

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  password: <%= ENV['USVERS_DATABASE_PASSWORD'] %>
  database: usvers
